# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c0fe852baf78c7a40a5c923e97419d2981d33ae23ef459d8359583f5f8fefbc18859bbeb5ad13543abd3953f968bbc60dc7993917bb66cbbee1cb0ab46bfb83

test:
  secret_key_base: eee2d560ba4f98de6eaad5341cd4c0b3ce61f2d180c80cbc249a69fa5c95578ed64a49a2e44990a19b6bc974d3c9a8dfa550b5264ff015a9def440c5dcc8f913

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
